language: clojure
sudo: false
jdk:
- oraclejdk8
lein: 2.7.1
addons:
  rethinkdb: '2.3.6'
cache:
  directories:
  - "$HOME/.m2"
before_script:
  - "export JAVA_OPTS=-Xmx512m"
  - "echo $JAVA_OPTS"
  - lein clean
script:
- lein eastwood
- lein kibit
branches:
  only:
  - master
  - mainline
notifications:
  slack:
    secure: ARbvDz3oduvMPxFD5IwSgcygyajJJUQ8Vu9saa8RWuHuFjERT8Kh0KC9diKgISHgBZyRmUkiL+2hO/ICMg6R+CpFmkKfzZXZbLXeAL2yi3/Pm4vRVohhQFBDtYE9eby/yxSmKXcuBRpPdBTNilw3q+MITBOqn1lBZIBPKF5NgCakIEq+RSvv8ImSqqw1qKpAJrzBQpS3mriVEQJQgof70G1sY6RvCgCV5rvxiKD/xJp+qdSaVcT/qpTN5FZ/0dy+wSKjwOUOlr6FtbAjglrX5WnpHV072HTNtYqqdGa7n8MzxxN8N93F2ehC9xQqvYDg6O/OJjCz46idKV+TsYpi01aX0KAkuEelAhwhKhL/2TBN78Qf0edyKBEJqQHbYok7zNsbDUTblCOWgKqED/mAbC8BsmVgjpRlDcxtyxIDu1j3Fo8qXVlMtckZVfqu+GCA3RlVenqHi/GenjyFTIqQjK/y9KwAMLkmXQQVHNv1praTI8x4nOSqYcdsH2yGaTSWnZME29mUMgdN4F7gZfXWAeg11w3kvWuagDTn53cpZbaHPDYp9cQ9JdMCW6DJuG28zC9hCJc5atlwgs0ljoDwqV9/CPQtmjfnq1nMyhEcYeSX20E0vTzHL370Y6qyz9jBCI1Iw7seG5ozcR5KKhDbrweXaXpGd5CsO70BYSwqwUw=